/*################################################################################
Project Name: <Batch Monitoring Automation>
File : <BatchAutomationConstants>
version: <1.0>
Created by : <Infosys Technologies>
Created Date: 7/27/2016
Last Modified By:<Infosys Technologies>
Last Modified Date:
Description:This class is to store constant values 

################################################################################*/
public Class BatchAutomationConstants
{
    public static final string nameSpace = 'http://www.force.com/2009/06/asyncapi/dataload';
    public static final string sampleAccessToken = '00D28000000c0K5!ARMAQN9W_o5S8l4AkSoBoEv.HNGrqfQBLMMQk00I3EYvVZBl7MZCpQFV3ZEDIzlwCmQxbKjeZHoelB0bJWClfqWPZNhDLlMO';
    public void sampleMethod()
    {
    }
}